/**
 * HTU University Structure
 * This file serves as the master source for all Faculties, Departments, and Programmes.
 * Used for dropdown selections to ensure data integrity.
 */

export interface HTUDepartment {
  name: string;
  programmes: string[];
}

export interface HTUFaculty {
  name: string;
  departments: HTUDepartment[];
}

export const HTU_STRUCTURE: HTUFaculty[] = [
  {
    name: "Faculty of Applied Sciences and Technology",
    departments: [
      {
        name: "Department of Agricultural Sciences and Technology",
        programmes: [
          "Agricultural Potential in Ghana",
          "Vegetable Crops Production",
          "Non-Ruminant Production",
          "Introduction to Soil Science",
          "Introduction to Economics",
          "Personal Development Planning",
          "Principles of Management",
          "Spices, Herbs and Aromatic Plants",
          "Soil and Water Management",
          "Fruit and Tree Crop Production",
          "Farm Accounting",
          "Business Mathematics",
          "Experimental Design and Analysis",
          "Postharvest Physiology and Management",
          "Principles of Marketing",
          "Agro Processing Technology",
          "Environmental Management",
          "Animal Health and Physiology",
          "Gender Issues in Agriculture",
          "Business Law",
          "Basic Genetics and Biotechnology",
          "Plant Physiology",
          "Anatomy & Physiology of Farm Animals",
          "Principles of Economics",
          "Mathematics for Agriculture",
          "Introductory Plant Pathology",
          "Irrigation System Management",
          "Agricultural Financial Accounting",
          "Agricultural Production and Managerial Economics",
          "Tree Crops Production",
          "Animal Health & Diseases",
          "Principles and Practices of Aquaculture",
          "Soil Fertility Management",
          "Agricultural Finance",
          "GIS and Remote Sensing Application",
          "Principles of Meat Science and Hygiene",
          "Agriculture and Climate Change",
          "Agricultural Marketing and Trade",
          "Risk Management in Agro Enterprises",
          "Agricultural Policy Analysis",
          "Entrepreneurship"
        ]
      },
      {
        name: "Department of Computer Science",
        programmes: [
          "Systems Administration",
          "Computer Organization and Architecture",
          "Information Security",
          "Computer Forensics",
          "Operating Systems",
          "Artificial Intelligence",
          "Data Science",
          "Wireless Communication",
          "Advanced Software Development with Java",
          "Computer Literacy",
          "Entrepreneurship & Innovation",
          "Introduction to Information Technology",
          "Discrete Mathematics",
          "Basic Electronics",
          "Fundamentals of Computer Science",
          "Computer Networking",
          "Database Systems and Design",
          "Digital Logic Design",
          "Web Application Programming",
          "Calculus",
          "Software Engineering",
          "IT Project Management",
          "Object-Oriented System Analysis and Design",
          "Research Methods in Computer Science",
          "Principles of Programming",
          "Programming with C++",
          "Principles of Economics",
          "Database Systems I",
          "Web Technology I",
          "Data Structures and Algorithms",
          "Data Communication and Networks I",
          "Management Information Systems",
          "Probability",
          "Principles of Accounting",
          "Programming with Python",
          "Server Administration I",
          "Multimedia Technology",
          "E-Commerce",
          "IT Auditing",
          "Electronic Procurement",
          "Communication Skills I",
          "Probability and Statistics",
          "Introduction to Computer Program Design",
          "Programming using Java",
          "Principles of Management",
          "Legal, Ethical and Professional Issues in Computer Science",
          "Introduction to Data Science",
          "Computer Applications",
          "Industrial Attachment",
          "Elements of Programming",
          "Introduction to Financial Accounting",
          "Fundamentals of ICT",
          "Database Development and Management",
          "Computer Graphics Design",
          "Programming with .NET Framework",
          "Introduction to Management"
        ]
      },
      {
        name: "Department of Food Science and Technology",
        programmes: [
          "Data Analysis",
          "Chemistry I",
          "General Biology",
          "Physics",
          "Mathematics",
          "Biochemistry and Metabolism",
          "Food Chemistry I",
          "Basic Microbiology",
          "Food Processing & Preservation I",
          "Food Law and Legislation",
          "Food Commodities",
          "Fruits and Vegetables Processing Technology",
          "Food Analysis II",
          "Cereal Processing Technology",
          "Sensory Evaluation",
          "Food Product Development",
          "Dairy Processing Technology",
          "Food Biotechnology",
          "Food Additives and Toxicology",
          "Introduction to Economics",
          "Food Plant Design and Economics",
          "Fats and Oils Processing Technology",
          "Techniques in Laboratory Analysis I",
          "Food Service Operations & Management",
          "General Chemistry",
          "Food Commodities I",
          "Food Analysis I",
          "Food Processing & Preservation",
          "Food Production Systems",
          "Emerging Trends in Food Science",
          "Food Safety",
          "Food Microbiology & Fermentation",
          "Project Seminar",
          "Principles of Marketing",
          "Principles of Management",
          "Practical Internship",
          "Research Methodology",
          "Entrepreneurship and Innovation",
          "Introduction to Statistics",
          "Food Crop Processing",
          "Sustainable Innovation in Food Science",
          "Traditional Food Processing Technology"
        ]
      },
      {
        name: "Department of Hospitality and Tourism Management",
        programmes: [
          "Introduction to Social Psychology",
          "Thematic Geography",
          "Mathematics",
          "French Language",
          "Integrated Science",
          "English Language",
          "Menu Planning",
          "Food Commodities",
          "Hygiene, Safety & First Aid",
          "Accommodation",
          "Food and Beverage Service",
          "Cookery (Theory/Practical)",
          "Accommodation (Theory & Practical)",
          "Front Office Operation I",
          "Hospitality Digital Marketing",
          "Accommodation Operation",
          "Communication Skills I",
          "Basic Statistics",
          "Entrepreneurship I",
          "Hospitality Engineering & Tourism Management",
          "Bar Operation & Management",
          "Accommodation Operation Management",
          "Food and Beverage Management",
          "Food Production Management",
          "Hospitality French",
          "Hospitality Accounting",
          "Introduction to Tourism",
          "Housekeeping Operations",
          "Food Innovation Systems",
          "Food and Beverage Service Operation",
          "Computer Literacy I",
          "Culinary Hygiene and Safety",
          "Food Science",
          "Foundations of Front Office Operations",
          "Fundamentals of Food and Beverage Service",
          "Introduction to Housekeeping",
          "Principles of Food Production",
          "Destination Management",
          "Eco-Tourism",
          "Event Project Management",
          "Event Administration",
          "Human Resource Management",
          "Strategic Management",
          "Economics of Tourism and Leisure",
          "Sociology of Leisure",
          "Tourism, Leisure & Event French",
          "Tourism, Leisure & Event Planning",
          "Tourist Psychology",
          "IT in Tourism, Leisure and Event Operations",
          "Accounting for Tourism, Leisure & Event",
          "Spirit and Mixology Management",
          "Restaurant Revenue Management",
          "Food Service Systems",
          "Food Factory Design and Operations",
          "Business Development",
          "Principles of Tourism",
          "Purchasing, Costing and Control",
          "Principles of Housekeeping",
          "Food Service Operations",
          "Food Production Principles",
          "Basic Food Production Operation",
          "Hospitality Corporate Social Responsibility",
          "Principles and Practice of Tourism",
          "Research Methodology",
          "Hospitality Cost and Accounting",
          "Entrepreneurship and Innovation",
          "Travel Geography",
          "Data Analysis",
          "Hospitality Marketing",
          "Hospitality Engineering and Maintenance",
          "Hospitality Internship",
          "Africa in the Modern World",
          "Introduction to Food Beverage Service",
          "Introduction to Hospitality & Tourism Studies",
          "Hospitality Engineering & Management",
          "Food Production Operation III",
          "Food Technology",
          "Hospitality Law",
          "Food and Beverage Service III",
          "Food and Beverage Service I"
        ]
      },
      {
        name: "Department of Mathematics and Statistics",
        programmes: [
          "Advance Database Management",
          "Stochatic Processes",
          "Advanced Statistical Methods",
          "Statistical Tool in Machine Learning",
          "Advance Multivariate Statistics",
          "Programming in Python",
          "Principles of Finance",
          "International Trade Finance",
          "Marketing of Financial Services",
          "Financial Management II",
          "Data Mining for Finance",
          "Investment Management",
          "Statistical Quality Control",
          "Multivariate Method & Analysis",
          "Applied Time Series Analysis",
          "Vector Algebra & Differential Equations",
          "Operations Research II",
          "Introduction to Sampling Techniques II",
          "Probability Distributions",
          "Design & Analysis of Experiments II",
          "Micro Finance & Rural Banking",
          "Calculus and Matrix Algebra",
          "Statistical & Financial Computing",
          "Applied Demography",
          "Introduction to Insurance",
          "Business Ethics",
          "Financial Management I",
          "Business and Commercial Law",
          "Financial Mathematics",
          "Principle of Economics 1",
          "Introduction to Probability",
          "Introduction to Statistics 1",
          "Element of Mathematics 1",
          "Demography",
          "Computer Literacy",
          "Introduction to Statistical Methods",
          "Introductory Mathematics 1"
        ]
      }
    ]
  },
  {
    name: "Faculty of Applied Social Sciences",
    departments: [
      {
        name: "Department of Economics and Innovation",
        programmes: [
          "Innovation Indicators and Policy",
          "History and Philosophy of Innovation Management",
          "Mathematics for Economics",
          "Principles of Microeconomics",
          "Environmental and Resource Economics",
          "International Economics and Innovation",
          "Theories and Applications of Econometrics I",
          "Intellectual Property Management",
          "Development Economics",
          "Practical 4 : Problems Classes and Skills Learning I",
          "Managerial Economics and Business Strategy",
          "Entrepreneurial Economics, Innovation and Self-Employment I",
          "Statistical Methods for Economics and Innovation",
          "Law and the Economy",
          "Practical 2: Case Studies and Skills Learning I",
          "Innovation Systems and Strategies",
          "Intermediate Microeconomics"
        ]
      },
      {
        name: "Department of Applied Modern Languages and Communication",
        programmes: [
          "Basic French I",
          "Basic Chinese I",
          "Communication Skills I",
          "Advertising and the Consumer Culture",
          "Visual Communication and Culture",
          "Media and Technology",
          "Media and Social Constructs",
          "Media Ethics and Law",
          "Introduction to Corporate Communication",
          "Digital Platform Management",
          "Techniques of Multimedia Journalism",
          "Introduction to Media Technology"
        ]
      },
      {
        name: "Department of Multidisciplinary Studies",
        programmes: [
          "Entrepreneurship & Innovation",
          "Entrepreneurship Development I",
          "Issues in Africa Population and Development",
          "Chieftaincy and Development in Africa",
          "Culture and Development in Africa",
          "Africa in the Diaspora",
          "Africa in the Modern World",
          "Business Research Methods",
          "Research Methods"
        ]
      }
    ]
  },
  {
    name: "Faculty of Art and Design",
    departments: [
      {
        name: "Department of Fashion Design & Textiles",
        programmes: [
          "Research Methods",
          "Dyeing Technology",
          "Weaving/Knitting Technology",
          "Computer-Aided Textiles Decoration Processes",
          "Printing Technology",
          "Computer-Aided in Fashion Arts & Crafts",
          "Fashion Arts and Crafts",
          "Millinery/Accessories Design & Production",
          "Fashion & Textile Marketing",
          "Quality Control",
          "Computer-Aided Pattern Alteration & Grading",
          "Fashion Presentation & Portfolio Development",
          "Construction of Draped Garments",
          "Draping Adaption",
          "Fashion Accessories",
          "Tailored Jackets Construction",
          "Tailored Jacket Patterns Development",
          "Digital Fashion Design & Illustration with CorelDraw",
          "Fashion and Textiles Merchandising",
          "Computer-Aided Design in Textiles",
          "Fashion Products Development",
          "Embroidery and Appliqué",
          "Production Management",
          "Construction of Draped and Reversed Engineering Patterns",
          "Draping & Reversed Engineering Techniques of Pattern Drafting",
          "Tailored Clothing Construction",
          "Tailored Pattern Development",
          "Textiles Design",
          "Textile Fibres and Yarn Preparation",
          "Textiles Dyeing",
          "Weaving",
          "Basic Fashion Design & Illustration",
          "Introductory Garment Technology",
          "Flat Pattern Making",
          "Design Brief and Collection I",
          "Production and Operations Management",
          "Research Application",
          "Fashion Accessories Production",
          "Beauty Therapy & Wellness",
          "Textiles Decoration",
          "Construction of Reversed Engineering & Graded Patterns",
          "Reversed Engineering Pattern Making & Grading",
          "Computer-Aided Fashion Design & Pattern Development",
          "Fashion Supply Chain",
          "Fashion Figure Composition",
          "Tailored Trouser Production",
          "Tailored Trouser Patterns",
          "Production of Skirts and Dresses",
          "Skirts and Dress Patterns",
          "Fashion Media Development",
          "History of Fashion",
          "Fashion Illustration",
          "Construction of Children Dresses",
          "Flat Pattern Making-Children",
          "Basic Fashion Design"
        ]
      },
      {
        name: "Department of Industrial Arts",
        programmes: [
          "Ceramic Raw Materials",
          "Introductory Ceramic Chemistry",
          "History of Traditional Ghanaian Pottery",
          "Introduction to Studio Ceramics",
          "Introduction to Mould Making",
          "Basic Design",
          "Computer Aided Design",
          "Finishing and Firing Techniques",
          "Structural Clay Products",
          "Ceramic Bodies, Composition and Uses",
          "Hand Forming Techniques",
          "Kiln Design & Construction Technology",
          "Ceramic Printing Processes",
          "Tableware Production",
          "Contemporary Ceramics",
          "3D Computer Ceramic Design",
          "Ceramic Products Installation",
          "Project Presentation in Art",
          "Production and Operations Management",
          "Introduction to Art History",
          "Introduction to Painting",
          "Introduction to Graphic Design",
          "General Drawing",
          "History of Design",
          "Vector Graphics",
          "Introduction to Typography",
          "Industrial Printing Processes",
          "Introduction to Photography",
          "Advertising and Media Technology",
          "Drawing and Illustration",
          "Visual Communication",
          "2D Animation Graphics",
          "Advertising and Public Relations",
          "Applied and Motion Photography",
          "Packaging Design",
          "Bookbinding Processes",
          "3D Graphics",
          "Advanced Packaging Design",
          "Web Design Processes",
          "Multimedia",
          "Book Design Layout",
          "History of Pre-Colonial Painting in Africa",
          "Spatial Design",
          "Thematic Composition",
          "Introduction to Portraiture",
          "Digital Painting",
          "Experimental Painting",
          "Advanced Figure Painting",
          "History of Painting in the African Diaspora",
          "Printmaking",
          "Materials and Methods",
          "Introduction to Museum Studies",
          "Printing Technology",
          "Industrial Painting",
          "Modelling and Casting (In-the-round)",
          "Carving In-the-round",
          "Drawing (Figure I)",
          "History of Ancient African Sculpture",
          "Materials and Methods of Sculpture",
          "Computer Aided Sculpture",
          "Carving",
          "Modelling and Casting (Bust Production)",
          "Sculpture Working Drawing",
          "History of Global Art",
          "Assemblage and Construction",
          "Indigenous African Carving",
          "Digital Sculpture",
          "Integrated Carving Production",
          "Integrated Modeling and Casting",
          "Multi-media Sculpture",
          "Introduction to Textile Design",
          "Introduction to Cotton Yarn Production",
          "Fabric Structure",
          "Computer Application in Textile Design",
          "History of Textile Design",
          "Printed Textile Designs",
          "Dyes and Dyeing Processes",
          "Regenerated Natural Polymers",
          "Knitting Technology",
          "Weaving Mechanism",
          "Chemical Processing",
          "African Print Designs",
          "Advanced Fabric Structure",
          "Textile Printing",
          "Advanced Yarn Manufacture",
          "Weaving Technology",
          "Oriental Art and Classical Ceramic History",
          "Refractory Technology",
          "Colloids in Ceramics",
          "Introduction to 3D Computer Design",
          "Advanced Studio Ceramics",
          "Occupational Health & Safety in Art",
          "3D Computer Graphics",
          "Applied Digital Illustration",
          "Digital Photography",
          "Fundamentals of Packaging",
          "History of Ancient Painting",
          "Introduction to Still Life Drawing",
          "Art Therapy",
          "Philosophy of Painting",
          "Independent Figure Painting",
          "Creative Painting",
          "Introduction to Digital Painting",
          "Realistic Modelling and Casting",
          "Interior and Furniture Design",
          "History of Modern Sculpture",
          "Purification Processes",
          "Textile Calculation and Loom Mechanism",
          "Foundation Studies in Textiles",
          "Non-Woven Fabrics"
        ]
      }
    ]
  },
  {
    name: "Faculty of Built & Natural Environment",
    departments: [
      {
        name: "Department of Architecture & Real Estates",
        programmes: [
          "Architectural Theory and Conservation",
          "Construction Technology I: Building Materials",
          "Introduction to Architectural Photography",
          "Introduction to Architectural Journalism",
          "Architectural Technology Lab I: Forms of Expression",
          "Geo Design I",
          "Integrated Building Services I: Waste Management and Recycling",
          "Construction Technology III: Superstructure",
          "Digital Communication for Building Design II: CAD Software",
          "Sustainable, Resilient & Universal Design",
          "Architectural Health Study I",
          "Introduction to Land Surveying",
          "Architectural Technology Lab III: Specification and Detailing",
          "Digital Communication for Building Design IV: Augmented / Virtual Environments & BIM",
          "Integrated Building Services III: Electrical, Mechanical and Intelligent Technologies",
          "Contract Management and Tendering",
          "Design Economics",
          "Community Survey",
          "Architectural Technology Lab V: Brown Spaces, Green Spaces and Adaptive Reuse",
          "Planning, Environmental and Construction Law",
          "Integrated Building Services IV: HVAC and Energy Technologies",
          "Professional Practice and Conduct in Architecture",
          "Project Planning and Control",
          "Building Analysis I",
          "Coding for Architectural Technology I",
          "Research Applications",
          "Architectural Technology Lab VII: Parasites on Land and Water",
          "Introduction to Facilities Management I",
          "Introduction to General Principles of Law",
          "Introduction to People Management",
          "Building Materials",
          "Construction Technology I",
          "Building Services I",
          "Space Planning",
          "Building Science",
          "Financial Management",
          "Real Estate Finance",
          "Procurement Management",
          "Facilities Change Management",
          "Risk and Property Insurance",
          "Energy Management and Audit",
          "Occupational Health and Safety",
          "Marketing Facilities Management Services",
          "Security Services for Facilities Management",
          "Research Techniques in Facilities Management I",
          "Customer Service",
          "Ethics and Professional Practice",
          "Research Methods",
          "Entrepreneurship and Innovation",
          "Business Development"
        ]
      },
      {
        name: "Department of Building Technology",
        programmes: [
          "Building Law",
          "Entrepreneurship I",
          "Technical Report Writing",
          "Computer Application",
          "Project Planning and Control",
          "Measurement of Construction Works III",
          "Building Management",
          "Building Law I",
          "Construction Technology V",
          "Environmental Impact of Construction Activities",
          "Computer Aided Design Application",
          "Site Organisation & Procedures",
          "Construction Estimating",
          "Construction Technology III",
          "Land Surveying III",
          "Building Services I",
          "Measurement of Constructions Work I",
          "Communication Skills I",
          "Computer Literacy I",
          "Construction Technology I",
          "Building Drawing",
          "Building Materials I",
          "Building Science I",
          "Strength of Materials I",
          "African Studies",
          "Building Mathematics I",
          "Renewable Energy Technology",
          "Human Resource Management",
          "Integrated Project Work I",
          "Measurement of Civil Engineering Works",
          "Construction Marketing",
          "Building Maintenance",
          "Project Cost Management",
          "Plant & Maintenance Management",
          "Entrepreneurship and Innovation",
          "Building Law II",
          "Engineering Technical Report Writing",
          "Practical Project V",
          "Measurement of Specialist Works III",
          "Construction Management",
          "Research Methodology",
          "Engineering Surveying",
          "Practical Project",
          "Building Mathematics",
          "Research Methods"
        ]
      },
      {
        name: "Department of Environment Science",
        programmes: [
          "Data Science",
          "Environmental Remediation Technologies",
          "Hospitality Industry and the Environment",
          "Environmental Modelling",
          "Applied Remote Sensing",
          "Environmental Analysis",
          "Statistics and Probability",
          "Introduction to Environmental Toxicology",
          "Fundamentals of Waste Management",
          "Introduction to Geographic Information Systems",
          "Environmental Technologies",
          "Instrument and Measurement",
          "Atmospheric Science",
          "Introduction to Sustainable Energy Resources",
          "Basic Electrical and Electronics",
          "Introduction to Microbiology",
          "Introductory Soil Science",
          "Principles of Physical Chemistry",
          "Engineering Mathematics I",
          "General Physics I",
          "General Chemistry I",
          "General Biology I"
        ]
      }
    ]
  },
  {
    name: "Faculty of Engineering",
    departments: [
      {
        name: "Department of Agricultural Engineering",
        programmes: [
          "Work Schedule Preparation and Implementation",
          "Repair and Maintenance of Agricultural Machines and Implements",
          "Entrepreneurship: Business Enterprise Establishment",
          "Personal Development Planning",
          "Research Methodology and Experimental Design",
          "Repair of Agricultural Machinery",
          "Soil and Water Conservation Engineering",
          "Entrepreneurship: Business Enterprise Identification",
          "Introduction to Precision Agriculture",
          "Rural Sociology and Agricultural Extension",
          "Farm Power and Machinery",
          "Food Crops Preservation",
          "Agricultural Tools and Implements Manufacture",
          "Irrigation Water Management",
          "Engineering Mathematics",
          "Basic Electricity and Electronics",
          "Principles of Material Science",
          "Workshop Technology",
          "Engineering Drawing",
          "Environmental Hydraulics",
          "Basic Mechanics",
          "Strength of Materials",
          "Computer Graphics / AutoCAD",
          "Introduction to Computer Programming",
          "Climate Change and Sustainable Development",
          "GIS and Remote Sensing for Environmental Engineering",
          "Soil Tillage",
          "Renewable Energy Systems Engineering",
          "Machine Design",
          "Agricultural Materials Handling",
          "Environmental Biotechnology",
          "Basic Farm Power and Machinery",
          "Water and Sanitation Engineering",
          "Agricultural and Environmental Robotics",
          "Drainage and Flood Control Engineering",
          "Agro Processing and Packaging",
          "Hydraulic Drive and Control",
          "Advanced Farm Power and Machinery",
          "Soil and Water Conservation"
        ]
      },
      {
        name: "Department of Civil Engineering",
        programmes: [
          "Research Methodology",
          "Advanced Water Treatment",
          "Systems Engineering",
          "Geotechnical Engineering",
          "Structural Engineering",
          "Highway Engineering",
          "Irrigation Engineering",
          "Final Year Project",
          "Civil Engineering Integrated Project",
          "Organizational Studies",
          "Health and Safety",
          "Building Services",
          "Construction Management",
          "Engineering Ethics",
          "Research Methodology & Technical Report Writing",
          "Numerical Analysis",
          "Estimation of Civil Engineering Works",
          "Building Information Modelling",
          "Steel and Timber Structure Design",
          "Foundation Engineering",
          "Soil Mechanics and Soil Engineering",
          "Construction Technology",
          "Engineering Surveying",
          "Theory of Structures",
          "Transportation Engineering",
          "Measurement of Civil Engineering Works",
          "Basic Mechanics",
          "Basic Drawing",
          "Basic Geology",
          "Strength of Materials",
          "Engineering Mathematics I",
          "Construction Accounting",
          "Theory of Structures & Reinforced Concrete Design",
          "Civil Engineering Construction",
          "Civil Engineering Drawing AutoCAD",
          "Water Supply and Distribution",
          "Sanitary Engineering",
          "Civil Engineering Maintenance",
          "Fluid Mechanics and Hydraulics",
          "Civil Engineering Materials & Site Organization Studies",
          "Principles of Surveying"
        ]
      },
      {
        name: "Department of Electrical and Electronic Engineering",
        programmes: [
          "Managing People at Work and Supervision",
          "Research Methods",
          "Mechatronic Systems Design",
          "Computer Controlled Systems",
          "Wireless and Mobile Communication",
          "Power System Operation and Control",
          "Project Work",
          "Digital Signal Processing",
          "Power Electronics",
          "Power System Analysis",
          "Robotics and Computer Vision",
          "Process Control and Automation",
          "RF and Microwave Engineering",
          "High Voltage Engineering",
          "Electrical Equipment Safety and Maintenance",
          "Advanced Control Systems",
          "Power Transmission and Distribution",
          "Signals and Systems",
          "Numerical Analysis",
          "Analogue Communication Systems",
          "Applied Thermodynamics",
          "Electrical Machines",
          "Electronic Devices and Circuits",
          "Python Programming",
          "Differential Equations",
          "Multivariable Calculus",
          "Engineering Mechanics",
          "Basic Electronics",
          "Applied Electricity",
          "Linear Algebra",
          "Frequency Response and System Analysis",
          "Wireless Communication Systems",
          "Engineering Project Management",
          "Electrical Installation Estimating and Costing",
          "Environmental Science and Management",
          "Digital Electronics",
          "Control System Components and Representations",
          "Power Systems Generation and Supply",
          "Direct Current Machines",
          "Electrical Engineering Drawing",
          "Applied Thermodynamics Heating and Cooling",
          "Electrical Measurement and Instrumentation",
          "Calculus",
          "Molecular Biology and Genetic Engineering",
          "Microprocessor and Interfacing",
          "Biomaterials and Artificial Organs",
          "Biosignal Processing",
          "Biomechanics",
          "Numerical Methods",
          "Introduction to Computer Programming",
          "Computer Aided Design",
          "Electronics Circuits I",
          "Digital Systems",
          "Biochemistry",
          "Thermodynamics",
          "Circuit Theory",
          "General Biology",
          "Introduction to Biomedical Engineering",
          "Physics",
          "Engineering Drawing I"
        ]
      },
      {
        name: "Department of Mechanical Engineering",
        programmes: [
          "Research Methods",
          "Project Work",
          "Instrumentation and Control",
          "Quality Control",
          "Jig and Tool Design",
          "Manufacturing Technology",
          "Management and Organization",
          "Production Planning and Control",
          "Mechanics of Machines",
          "Metrology",
          "Internal Combustion Engines",
          "Management and Control of Transport",
          "Automotive Electronics",
          "Automotive Workshop Practice",
          "Law of Business and Carriage",
          "Vehicle Technology",
          "Workshop Organization and Administration",
          "Principles of Machine Design",
          "Basic Electronics",
          "Automotive Electricals",
          "Internal Combustion Engine Principles",
          "Vehicle Structure and Suspension System",
          "Material Technology",
          "Advanced Calculus",
          "Thermodynamics I",
          "Strength of Materials",
          "Engineering Drawing",
          "Mechanics of Fluids",
          "Electrical Engineering",
          "Mathematical Foundations and Computational Tools",
          "Workshop Processes and Practices",
          "Maintenance Engineering",
          "Engineering Ethics and Safety",
          "Cutting Tools Design",
          "Mechatronics",
          "CAD/CAM",
          "Quality Assurance",
          "Engineering Economy and Management",
          "Production Engineering",
          "Jigs and Fixture Design",
          "Industrial Engineering and Ergonomics",
          "Hydraulics and Pneumatics",
          "Design and Fabrication Project",
          "Automation and Process Control",
          "Machine Design",
          "Engineering Mathematics III",
          "Engineering Mechanics Dynamics",
          "Basic French I",
          "Engineering Mechanics Statics",
          "Real and Complex Number Systems",
          "Diagnostics of Vehicles with Electronic Management Systems",
          "Power Train Technologies and E-Mobility",
          "Management Accounting and Finance",
          "Electronic Vehicle Management Systems",
          "Automotive Design and Manufacturing Techniques",
          "People Management at Work and Supervision",
          "Automotive Chassis Electronics",
          "Automotive Hydraulics and Pneumatics",
          "Automotive Electrical Systems",
          "Spark Ignition Engines",
          "Matrix Algebra and Differential Equations"
        ]
      }
    ]
  },
  {
    name: "HTU Business School",
    departments: [
      {
        name: "Department of Accounting and Finance",
        programmes: [
          "Accounting System Design",
          "International Finance",
          "Financial Econometrics",
          "Electronic & Internet Banking",
          "Tax Audit & Investigation",
          "Oil, Gas & Other Minerals Taxation",
          "Principles of International Taxation",
          "Corporate Reporting",
          "Audit and Assurance",
          "Public Sector Accounting",
          "Risk Management",
          "Portfolio & Investment Management",
          "Corporate Finance",
          "Indirect Taxation",
          "Public Sector Economics and Finance",
          "Income Taxation",
          "Financial Reporting",
          "Cost and Management Accounting",
          "Fundamentals to Public Administration",
          "Financial Accounting",
          "Electronic Commerce",
          "Business Ethics and Corporate Governance",
          "Logic and Critical Thinking",
          "Quantitative Methods for Business Studies",
          "Information Literacy",
          "Business Communication",
          "Mathematics for Business Studies",
          "Money, Banking, and Financial Markets",
          "Digital Banking",
          "Business Law",
          "Banking Operations",
          "Microfinance & Rural Banking",
          "Strategic Information Management",
          "Business Policy & Corporate Strategy",
          "Data Analysis & Financial Software",
          "International Trade Finance & Insurance",
          "Microeconomics for Business Decisions",
          "Financial Statements Analysis",
          "Principles of Accounting",
          "Principles and Practice of Insurance",
          "Introduction to Finance, Banking and Insurance",
          "Investment Management",
          "Principles of Financial Management",
          "Credit Management",
          "Treasury Management",
          "Corporate Governance",
          "Business Ethics",
          "Quantitative Methods",
          "Marketing of Financial Services",
          "Management Information System",
          "Financial Markets, Institutions & Monetary Economics",
          "Financial Reporting for Corporate Business",
          "Basic Mathematics",
          "Principles and Elements of Business Law",
          "Introduction to Micro Economics",
          "Principles of Financial Accounting",
          "Accounting",
          "Auditing and Assurance Services",
          "Auditing & Investigation",
          "Business Environment",
          "Financial Risk Management",
          "Management",
          "Cost Accounting",
          "Business Economics"
        ]
      },
      {
        name: "Department of Logistics and Supply Chain Management",
        programmes: [
          "Procurement Context",
          "Business Communication",
          "Entrepreneurship and Small Business Management",
          "Marketing",
          "Organizational Behavior",
          "Economics",
          "Inventory and Warehouse Management",
          "Retail Supply Chain Management",
          "Business Economics",
          "Understanding Business Needs",
          "Introduction to Supply Chain Management",
          "Information Literacy",
          "Business Law",
          "Management Principles and Practice",
          "Negotiation Science",
          "Supply Chain Relationships Management",
          "Decision Science",
          "Procurement Audit",
          "Public Sector Procurement",
          "Global Sourcing & International Logistics",
          "Supply Chain Finance",
          "Total Quality Management",
          "Strategic Supply Chain Management",
          "Supply Chain Modeling & Optimization",
          "E-Procurement & Supply Chain Management",
          "Quantitative Methods",
          "Introduction to Procurement Management",
          "Internal & External Relationships in Procurement",
          "Business & Public Administration",
          "Managing Purchasing and Supply Relationships",
          "Information Communication Technology",
          "Commercial Law",
          "Public Procurement: Act 663",
          "Managing and Securing Supplies",
          "Understanding Procurement Environment",
          "Negotiation in Procurement",
          "International Business Management",
          "Procurement in Action",
          "Managing Procurement Performance",
          "Business Research Methods"
        ]
      },
      {
        name: "Department of Management Sciences",
        programmes: [
          "Conference and Event Management",
          "Research Methods",
          "Introduction to Procurement Management",
          "Business Economics",
          "Computer Keyboard Techniques",
          "Business Statistics",
          "Fundamental French",
          "Advanced Computer Application",
          "Event Planning and Management",
          "Social Media Management",
          "Law and Procedures of Meeting",
          "Human Resource Management",
          "Administrative Law",
          "Practical Office Training",
          "Secretarial Practice",
          "Strategic Management",
          "Operations Management",
          "Secretarial French",
          "Cost and Management Accounting",
          "Organisational Behaviour",
          "Secretarial English",
          "Computer Applications",
          "Introduction to Business Communication",
          "Corporate and Civil Law",
          "Typewriting",
          "Quantitative Methods",
          "Introduction to Accounting",
          "Economics",
          "Corporate Secretarial Practice",
          "Industrial Relations",
          "Public Sector Management",
          "Corporate Governance and Ethics",
          "Management Information System",
          "Practical Office Training and Professional Practice",
          "Personality Development",
          "Office and Document Management System",
          "Business English",
          "Advanced Business French",
          "Document and Text Processing",
          "Professional Practice",
          "Database Management System",
          "Corporate Law and Governance",
          "Web Content Management",
          "Corporate Executive Secretarial Practice"
        ]
      },
      {
        name: "Department of Marketing",
        programmes: [
          "Entrepreneurship and Innovation",
          "Research Methodology",
          "Brand and Sports Marketing",
          "Customer Communication",
          "Marketing Research and Information System",
          "Fundamentals of Digital Marketing",
          "Introduction to System Analysis and Design",
          "Principles of Financial Accounting",
          "Business Environment",
          "Principles of Marketing",
          "Information Technology Literacy",
          "Business Communications",
          "Business Economics",
          "Integrated Marketing Communications",
          "Services Marketing",
          "Marketing Management and Strategies",
          "E-Tailing & Retail Management",
          "Database Administration",
          "Web Application Technology",
          "Business Development",
          "Marketing Analytics",
          "Sustainable Marketing and Business Development",
          "Events Marketing",
          "Sales Management and Strategy",
          "Fundamentals of Cyber Security",
          "Web Concept Technology",
          "Fundamentals of Sustainability Marketing",
          "Consumer Behaviour",
          "Business Statistics",
          "Principles of Computerized Accounting",
          "Legal Environment of Business",
          "Business Communications and Ethics",
          "Principles of Management and Public Administration",
          "Selling and Sales Management",
          "Marketing Communications",
          "Project Management",
          "International Marketing",
          "Marketing Management",
          "Marketing Planning & Control",
          "Management for Marketing",
          "Marketing/Customer Interface",
          "Management Information for Marketing Decisions",
          "Marketing Operations",
          "Behavioural Aspects of Marketing",
          "Financial Accounting",
          "Business Law",
          "Marketing Environment",
          "Quantitative Studies",
          "Economics",
          "Customer Communications",
          "Marketing Fundamentals"
        ]
      }
    ]
  },
  {
    name: "School of Graduate Studies",
    departments: [
      {
        name: "MTech Agric Engineering",
        programmes: ["Advanced Agricultural Engineering Studies"]
      },
      {
        name: "MTech Hospitality Management",
        programmes: ["Advanced Hospitality Management Studies"]
      },
      {
        name: "MTech Mechanical Engineering",
        programmes: ["Advanced Mechanical Engineering Studies"]
      },
      {
        name: "MTech Refrigeration and Air-Conditioning",
        programmes: ["Advanced Refrigeration and Air-Conditioning Studies"]
      },
      {
        name: "MSc. Food Science and Technology",
        programmes: [
          "Food Product Development",
          "Seminar I",
          "Traditional Food Processing Technology",
          "Sustainable Innovation in Food Science",
          "Agribusiness Development",
          "Food Crop Processing"
        ]
      }
    ]
  }
];
